name: Deploy to GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                token: ${{secrets.DEPLOY_TOKEN}}
            - uses: actions/setup-node@v3
            - run: make install
            - run: make deploy