name: Deploy to GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: make install
              name: Set up SSH
            - run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.AUTH_DEPLOY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                echo "Host github.com" >> ~/.ssh/config
                echo "  StrictHostKeyChecking no" >> ~/.ssh/config
              name: Deploy
            - run: |
                git remote set-url origin git@github.com:${{ github.repository }}.git
                make deploy
