name: Deploy to GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: make install
            - run: echo "machine github.com login PavelKochetkov password ${{ secrets.GITHUB_TOKEN }}" >> ~/.netrc
            - run: make deploy