name: Deploy to GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repository
            uses: actions/checkout@v3
          - name: Setup Node.js
            uses: actions/setup-node@v3
          - name: Install Dependencies
            run: make install
          - name: Setup SSH
            run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.AUTH_DEPLOY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                echo "Host github.com" >> ~/.ssh/config
                echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          - name: Configure Git user
            run: |
                  git config --global user.email "${{secrets.USER_EMAIL}}"
                  git config --global user.name "${{secrets.USER_NAME}}"
          - name: Deploy
            run: |
                git remote set-url origin git@github.com:${{ github.repository }}.git
                make deploy
