name: Deploy to GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                token: ${{secrets.DEPLOY_TOKEN}}
            - uses: actions/setup-node@v3
            - run: make install
            - run: git config user.name ${{ secrets.GIT_USER_NAME }}
            - run: git config user.email ${{ secrets.GIT_USER_EMAIL }}
            - run: echo "DEPLOY_TOKEN is set"
              env:
                DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

            - run: echo "GIT_USER_NAME is set"
              env:
                GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

            - run: echo "GIT_USER_EMAIL is set"
              env:
                GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
            - run: make deploy
