name: Deploy to GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: make install
            - run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan github.com >> ~/.ssh/known_hosts
            - run: |
                git config --global user.name Pavel Kochetkov
                git config --global user.email kochetkov_p@mail.ru
            - run: make deploy